POST http://127.0.0.1:8080/api/restaurants
Content-Type: application/json

{
  "name": "카테고리 추가 테스트",
  "address": "부산 기장군 장안읍 월내해안1길 1",
  "avgPrice": 15000,
  "minPrice": 10000,
  "maxPrice": 20000,
  "geohash": "temp_hash",
  "customTags": []
}